version: '3.8'

services:
  supermarket-api:
    build: supermarket-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://supermarket_db:3306/supermarket_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    restart: always
    depends_on:
      supermarket_db:
        condition: service_healthy
  supermarket_db:
    image: mysql:8.0.43
    ports:
      - "3307:3306"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_ROOT_PASSWORD: admin
      SPRING_DATASOURCE_PASSWORD: admin
      MYSQL_DATABASE: supermarket_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      timeout: 10s
      retries: 10

  supermarket_frontend:
    build: supermarket_frontend
    container_name: supermarket_frontend
    restart: unless-stopped
    depends_on:
      - supermarket-api
    ports:
      - "80:80"

  volumes:
    mysql_data: {}