services:
  supermarket_db:
    image: mysql:8.0
    container_name: supermarket_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: supermarket_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  supermarket_api:
    build: ./supermarket-api
    container_name: supermarket_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://supermarket_db:3306/supermarket_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - supermarket_db

  supermarket_frontend:
    build: ./supermarket-frontend
    container_name: supermarket_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - supermarket_api

volumes:
  mysql_data: