# fly.toml app configuration file generated for supermarket-api-jpdjcp-rough-thunder-2030 on 2026-01-22T11:46:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supermarket-api-jpdjcp'
primary_region = 'iad'

[build]

[deploy]

[http_service]
  internal_port = 8080
  force_https = true

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
