# fly.toml app configuration file generated for supermarket-api-jpdjcp on 2026-01-10T22:59:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supermarket-api-jpdjcp'
primary_region = 'iad'

[build]

[deploy]
restart_on_crash = false

[http_service]
  internal_port = 8080
  force_https = true

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  timeout = "2s"
  method = "GET"
  path = "/actuator/health"

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
