app = 'supermarket-api-jpdjcp'
primary_region = 'iad'

[build]

[deploy]
  max_restarts = 0

[http_service]
  internal_port = 8080
  force_https = true

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
