name: FRONTEND CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "supermarket-frontend/**"
      - ".github/workflows/frontend-ci-cd.yml"

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy frontend to Fly.io
        run: flyctl deploy --remote-only
        working-directory: supermarket-frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}